INSERT INTO "module" ("Uri","Name") values ('/tracking','Tracking');
INSERT INTO "module" ("Uri","Name") values ('/tempoary','Tempoary');
INSERT INTO "module" ("Uri","Name") values ('/transport','Transport');
INSERT INTO "module" ("Uri","Name") values ('/update','Update');
INSERT INTO "module" ("Uri","Name") values ('/view','View');
INSERT INTO "module" ("Uri","Name") values ('/pfbs','PFBS');
INSERT INTO "module" ("Uri","Name") values ('/cfbs','CFBS');
INSERT INTO "module" ("Uri","Name") values ('/equipment','Equipment');
INSERT INTO "module" ("Uri","Name") values ('/other','Other');
INSERT INTO "module" ("Uri","Name") values ('/oqa','OQA');
INSERT INTO "module" ("Uri","Name") values ('/misc','Misc');


INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/jpre'  ,'Job Prepare','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/jprec'  ,'Job Prepare Cancel','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/ji'  ,'Job In','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/jic'  ,'Job In Cancel','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/dcol'  ,'Data Collection','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/jo'  ,'Job Out','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/nonlotdc'  ,'Non Lot Dcoll','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/nonlotjic'  ,'Non Lot Job In Cancel','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/mvloc'  ,'Move To Location','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/bankout'  ,'Bank Out','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/backup'  ,'Back Up','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/skip'  ,'Skip','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/hold'  ,'Hold','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/runhold'  ,'Run Hold','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/release'  ,'Release','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/rework'  ,'Rework','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/merge'  ,'Merge','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/split'  ,'Split','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/presplit'  ,'Prepare Split','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/split-rework'  ,'Split-Rework','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/brokenwafer'  ,'Broken Wafer Procedure','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/altop'  ,'Eap Choose Alt Operation','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/eocap'  ,'EOCAP','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/lotstart'  ,'Lot Start','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tracking/lotstartnew'  ,'Lot Start New','/tracking');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/tempoary/wrc'  ,'Wrc New Part','/tempoary');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/transport/shopfloor' ,'Shopfloor Query','/transport');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/update/lot'    ,'Update Lot','/update');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/update/lotcmt'    ,'Update Lot Comment','/update');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/update/eqprunlot'    ,'Update Eqp Running Lot List','/update');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/update/pwd'    ,'Change Password','/update');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/update/taginfo'    ,'Taginfo Update','/update');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/update/taginfolot'    ,'Taginfo Update Lot','/update');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/update/taginfodmylot'    ,'Taginfo Update Dummy Lot','/update');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/view/runstatus'      ,'Run Status Inquiry','/view');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/view/eqpstatus'      ,'Eqp Status Inquiry','/view');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/view/nonlotreport'      ,'Non Lot Generally Report','/view');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/view/futurehold'      ,'View Future Hold Lot','/view');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/view/gotoweb'      ,'Go To Web','/view');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/pfbs/ji'      ,'PFBS Job In','/pfbs');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/pfbs/jic'      ,'PFBS Job In Cancel','/pfbs');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/pfbs/dcol'      ,'PFBS Data Collection','/pfbs');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/pfbs/jo'      ,'PFBS Job Out','/pfbs');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/cfbs/ji'      ,'CFBS Job In','/cfbs');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/cfbs/jic'      ,'CFBS Job In Cancel','/cfbs');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/cfbs/dcol'      ,'CFBS Data Collection','/cfbs');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/cfbs/jo'      ,'CFBS Job Out','/cfbs');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/equipment/changestatus' ,'Equipment Status Change','/equipment');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/dispatch'     ,'Dispatch Query & Pull','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/rtclstatqry'     ,'Reticle Status Query','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/rtcltakeout'     ,'Reticle Takeout/Return','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/rtcleqp'     ,'Reticle/EqpId Maint.','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/rtclpart'     ,'Reticle/PartId Maint.','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/rtclpartqry'     ,'Reticle/PartId Query','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/rtclhistqry'     ,'Reticle Hist Query','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/rtclrtn'     ,'Reticle Return Confirmation','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/rtclstaus'     ,'Reticle Status Change','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/rtclacc'     ,'Reticle Acceptance','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/rtcluser'     ,'Reticle User Maint.','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/rtcllot'     ,'Reticle Query Lot-Reticle','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/prodreticle'     ,'View PROD Reticle','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/lotmask'     ,'Lot Mask','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/other/lotmaskqry'     ,'Lot Mask Query','/other');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/oqa/split'       ,'SPDN Split','/oqa');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/oqa/query'       ,'SPDN Query','/oqa');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/oqa/spec'       ,'SPDN Spec','/oqa');
INSERT INTO "function" ("Uri","Name","ModuleName") values ('/misc/eap'      ,'GO EAP','/misc');

