INSERT INTO "module" ("uri","name") values ('/tracking','Tracking');
INSERT INTO "module" ("uri","name") values ('/tempoary','Tempoary');
INSERT INTO "module" ("uri","name") values ('/transport','Transport');
INSERT INTO "module" ("uri","name") values ('/update','Update');
INSERT INTO "module" ("uri","name") values ('/view','View');
INSERT INTO "module" ("uri","name") values ('/pfbs','PFBS');
INSERT INTO "module" ("uri","name") values ('/cfbs','CFBS');
INSERT INTO "module" ("uri","name") values ('/equipment','Equipment');
INSERT INTO "module" ("uri","name") values ('/other','Other');
INSERT INTO "module" ("uri","name") values ('/oqa','OQA');
INSERT INTO "module" ("uri","name") values ('/misc','Misc');


INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/jpre'  ,'Job Prepare',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/jprec'  ,'Job Prepare Cancel',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/ji'  ,'Job In',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/jic'  ,'Job In Cancel',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/dcol'  ,'Data Collection',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/jo'  ,'Job Out',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/nonlotdc'  ,'Non Lot Dcoll',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/nonlotjic'  ,'Non Lot Job In Cancel',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/mvloc'  ,'Move To Location',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/bankout'  ,'Bank Out',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/backup'  ,'Back Up',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/skip'  ,'Skip',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/hold'  ,'Hold',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/runhold'  ,'Run Hold',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/release'  ,'Release',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/rework'  ,'Rework',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/merge'  ,'Merge',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/split'  ,'Split',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/presplit'  ,'Prepare Split',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/split-rework'  ,'Split-Rework',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/brokenwafer'  ,'Broken Wafer Procedure',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/altop'  ,'Eap Choose Alt Operation',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/eocap'  ,'EOCAP',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/lotstart'  ,'Lot Start',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tracking/lotstartnew'  ,'Lot Start New',1);
INSERT INTO "functions" ("uri","name","module_id") values ('/tempoary/wrc'  ,'Wrc New Part',2);
INSERT INTO "functions" ("uri","name","module_id") values ('/transport/shopfloor' ,'Shopfloor Query',3);
INSERT INTO "functions" ("uri","name","module_id") values ('/update/lot'    ,'Update Lot',4);
INSERT INTO "functions" ("uri","name","module_id") values ('/update/lotcmt'    ,'Update Lot Comment',4);
INSERT INTO "functions" ("uri","name","module_id") values ('/update/eqprunlot'    ,'Update Eqp Running Lot List',4);
INSERT INTO "functions" ("uri","name","module_id") values ('/update/pwd'    ,'Change Password',4);
INSERT INTO "functions" ("uri","name","module_id") values ('/update/taginfo'    ,'Taginfo Update',4);
INSERT INTO "functions" ("uri","name","module_id") values ('/update/taginfolot'    ,'Taginfo Update Lot',4);
INSERT INTO "functions" ("uri","name","module_id") values ('/update/taginfodmylot'    ,'Taginfo Update Dummy Lot',4);
INSERT INTO "functions" ("uri","name","module_id") values ('/view/runstatus'      ,'Run Status Inquiry',5);
INSERT INTO "functions" ("uri","name","module_id") values ('/view/eqpstatus'      ,'Eqp Status Inquiry',5);
INSERT INTO "functions" ("uri","name","module_id") values ('/view/nonlotreport'      ,'Non Lot Generally Report',5);
INSERT INTO "functions" ("uri","name","module_id") values ('/view/futurehold'      ,'View Future Hold Lot',5);
INSERT INTO "functions" ("uri","name","module_id") values ('/view/gotoweb'      ,'Go To Web',5);
INSERT INTO "functions" ("uri","name","module_id") values ('/pfbs/ji'      ,'PFBS Job In',6);
INSERT INTO "functions" ("uri","name","module_id") values ('/pfbs/jic'      ,'PFBS Job In Cancel',6);
INSERT INTO "functions" ("uri","name","module_id") values ('/pfbs/dcol'      ,'PFBS Data Collection',6);
INSERT INTO "functions" ("uri","name","module_id") values ('/pfbs/jo'      ,'PFBS Job Out',6);
INSERT INTO "functions" ("uri","name","module_id") values ('/cfbs/ji'      ,'CFBS Job In',7);
INSERT INTO "functions" ("uri","name","module_id") values ('/cfbs/jic'      ,'CFBS Job In Cancel',7);
INSERT INTO "functions" ("uri","name","module_id") values ('/cfbs/dcol'      ,'CFBS Data Collection',7);
INSERT INTO "functions" ("uri","name","module_id") values ('/cfbs/jo'      ,'CFBS Job Out',7);
INSERT INTO "functions" ("uri","name","module_id") values ('/equipment/changestatus' ,'Equipment Status Change',8);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/dispatch'     ,'Dispatch Query & Pull',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/rtclstatqry'     ,'Reticle Status Query',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/rtcltakeout'     ,'Reticle Takeout/Return',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/rtcleqp'     ,'Reticle/EqpId Maint.',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/rtclpart'     ,'Reticle/PartId Maint.',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/rtclpartqry'     ,'Reticle/PartId Query',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/rtclhistqry'     ,'Reticle Hist Query',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/rtclrtn'     ,'Reticle Return Confirmation',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/rtclstaus'     ,'Reticle Status Change',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/rtclacc'     ,'Reticle Acceptance',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/rtcluser'     ,'Reticle User Maint.',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/rtcllot'     ,'Reticle Query Lot-Reticle',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/prodreticle'     ,'View PROD Reticle',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/lotmask'     ,'Lot Mask',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/other/lotmaskqry'     ,'Lot Mask Query',9);
INSERT INTO "functions" ("uri","name","module_id") values ('/oqa/split'       ,'SPDN Split',10);
INSERT INTO "functions" ("uri","name","module_id") values ('/oqa/query'       ,'SPDN Query',10);
INSERT INTO "functions" ("uri","name","module_id") values ('/oqa/spec'       ,'SPDN Spec',10);
INSERT INTO "functions" ("uri","name","module_id") values ('/misc/eap'      ,'EAP',11);

